[package]
name = "tauri-plugin-tokyo"
version = "0.0.0"
authors = ["You"]
description = ""
edition = "2024"
links = "tauri-plugin-tokyo"

[target]

[dependencies]
tauri = { version = "2.0.0-beta" }
serde = "1.0"
serde_json = "1.0.105"
thiserror = "1.0"
tokyo-proto = { path = "../proto", features = ["protoc"] }
tokyo-library = { path = "../library" }
tokyo-shadow = { path = "../shadow" }
anyhow = "1.0.75"
tokio = { version = "1.35.0", features = ["rt", "rt-multi-thread", "macros"] }
env_logger = "0.10.1"
log = "0.4.20"

[build-dependencies]
tauri-build = { version = "2.0.0-beta" }
tauri-plugin = { version = "2.0.0-beta", features = ["build"] }
