[package]
name = "tokyo-proto"
version = "0.1.0"
edition = "2024"

[features]
protoc = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = { version = "3.5.0", features = ["with-bytes"] }
bytes = "1"

[build-dependencies]
protobuf-codegen = "3.5.0"

[[bin]]
name = "force-build"
path = "build.rs"
