[package]
name = "desktop"
version = "0.0.0"
description = "A Tauri App"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [ "macos-private-api",
    "devtools",
] }
tauri-plugin-os = "2"
tauri-plugin-tokyo = { path = "../../packages/tauri-plugin-tokyo" }
tauri-plugin-shade = { path = "../../packages/tauri-plugin-shade" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
window-vibrancy = "0.5"
tokyo-library = { path = "../../packages/library" }
tokio = "1.32.0"
futures = "0.3.30"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
