# https://taskfile.dev

version: "3"

includes:
  ui: ../ui/Taskfile.yml

tasks:
  tauri:dev:
    dir: ./
    cmds:
      - cargo tauri dev

  tauri:build:
    dir: ./
    cmds:
      - cargo tauri build

  dev:
    desc: Dev
    prefix: "desktop"
    dir: ./
    deps: [ui:build]
    cmd: task --parallel ui:dev tauri:dev

  build:
    desc: Build app
    dir: ./
    cmds:
      - task: ui:build
      - task: tauri:build

  start:
    desc: Start app production build
    dir: ../../target/release
    cmds:
      - ./app
