# https://taskfile.dev

version: "3"

includes:
  ui: ../ui/Taskfile.yml

tasks:
  dev:
    dir: ./
    cmds:
      - cargo tauri dev

  build:
    desc: Build app
    dir: ./
    cmds:
      - task: ui:build
      - cargo tauri build

  start:
    desc: Start app production build
    dir: ../../target/release
    cmds:
      - ./app
