[package]
name = "tokyo-schema"
version = "0.1.0"
edition = "2024"

[features]
protoc = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = { version = "3.7.2", features = ["with-bytes"] }
bytes = "1"
tonic = "0.14.2"
prost = "0.14.1"
tonic-prost-build = "0.14.2"

[build-dependencies]
tonic-prost-build = "0.14.2"
protobuf-codegen = "3.7.2"

[[bin]]
name = "force-build"
path = "build.rs"
