# https://taskfile.dev

version: "3"

tasks:
  setup:
    desc: Install dependencies
    cmds:
      - bun install

  dev:
    desc: Run website dev server
    prefix: "library"
    cmds:
      - bun x astro dev

  build:
    desc: Build website
    deps: [setup]
    sources:
      - "src/**/*.astro"
      - "src/**/*.ts"
    cmds:
      # - bun x astro check
      - bun x astro build {{.CLI_ARGS}}

  start:
    desc: Run website preview
    deps: [build]
    cmds:
      - bun x astro preview
