[package]
name = "tokyo-shadow"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
rawler = { git = "https://github.com/luckydye/dnglab", rev = "c088515" }
tokio = "1.32.0"
image = "0.24.7"
anyhow = "1.0.75"
srgb = "0.3.2"
kolor = "0.1.9"
env_logger = "0.10.1"
log = "0.4.20"
kitty_image = "0.1.0"

[profile.dev]
opt-level = 3
